# Generated by Django 2.0.10 on 2019-02-14 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190214_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='masked_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, verbose_name='masked_id'),
        ),
    ]
